server:
  port: 8082

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  observations:
    key-values:
      host: "core-module"
      instance: "core-pod"
      region: "ap-northeast-2"
      stack: "dev"