server:
  port: 8082

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: new1234!
    driverClassName: org.postgresql.Driver

management:
  tracing:
    sampling:
      probability: 1.0

api:
  tracing:
    grpc-collector: http://localhost:4317