server:
  port: 8082

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: new1234!
    driverClassName: org.postgresql.Driver

management:
  endpoint:
    health:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

api:
  tracing:
    grpc-collector: http://localhost:4317